### ISSUE TITLE
e2e-test reports InvalidRequest

### ISSUE THREAD

**Issue by gavin-ygy** [gevulotnetwork/gevulot#199]
The test program  gevulot/crates/tests/e2e-tests/src/main.rs  reports "thread 'main' panicked at crates/tests/e2e-tests/src/main.rs:94:10:
send_transaction: InvalidRequest("failed to persist transaction")" . 

$ RUST_LOG=debug  ./gevulot-e2e-tests --prover-img ~/.ops/images/prover  --verifier-img  ~/.ops/images/verifier --key-file my-local-key.pki --listen-addr 127.0.0.1:8080 --json-rpc-url http://api.devnet.gevulot.com:9944
[2024-06-18T09:54:39Z INFO  gevulot_e2e_tests] e2e is running....
Listening on http://127.0.0.1:8080
[2024-06-18T09:54:39Z INFO  gevulot_e2e_tests] before deployment:
[2024-06-18T09:54:39Z DEBUG gevulot_node::types::transaction] Transaction::new tx:4e5d71428b7eeaea12e293cd968bf2a21027e58fbe5e333a0cf3712cdbb76178 payload:(Deploy)
[2024-06-18T09:54:39Z DEBUG hyper::client::connect::dns] resolving host="api.devnet.gevulot.com"
[2024-06-18T09:54:39Z DEBUG hyper::client::connect::http] connecting to 34.88.251.176:9944
[2024-06-18T09:54:40Z DEBUG hyper::client::connect::http] connected to 34.88.251.176:9944
[2024-06-18T09:54:40Z DEBUG hyper::proto::h1::io] flushed 1535 bytes
[2024-06-18T09:54:40Z DEBUG hyper::proto::h1::io] parsed 3 headers
[2024-06-18T09:54:40Z DEBUG hyper::proto::h1::conn] incoming body is content-length (92 bytes)
[2024-06-18T09:54:40Z DEBUG hyper::proto::h1::conn] incoming body completed
[2024-06-18T09:54:40Z DEBUG hyper::client::pool] pooling idle connection for ("http", api.devnet.gevulot.com:9944)
thread 'main' panicked at crates/tests/e2e-tests/src/main.rs:100:10:
send_transaction: InvalidRequest("failed to persist transaction")

**Comment by gavin-ygy** [comment]
The e2e test need a local Gevulot node  or  you should customize the  client software ,please refer to https://github.com/0xEigenLabs/eigen-estark-gevulot/blob/main/tests/e2e-test/src/main.rs
